FROM python:3.9

RUN mkdir -p /application
WORKDIR /modele_propre

COPY requirements.txt ./requirements.txt
RUN pip install -U pip
RUN pip install -U wheel
RUN pip install -U setuptools
RUN apt-get update
RUN apt-get install libasound-dev libportaudio2 libportaudiocpp0 portaudio19-dev -y
RUN pip install pyaudio
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8501

CMD ["streamlit","run","application.py"]